### ISSUE TITLE
Luet check repo timestamp

### ISSUE THREAD

**Issue by joostruis** [mudler/luet#274] opened 2021-12-08 17:06 UTC
If we search for a package with luet, by default it will try to check for latest repo versions.

`xbox-360 /home/joost # time luet search kde -q

INFO:  Downloaded repository.yaml of 0.00 MB ( 0.01 MiB/s )
INFO:  Repository luet-official is already up to date.
INFO:  ℹ  Repository: luet Priority: 1 Type: http
INFO:  Downloading quay.io/mocaccino/mocaccino-community:repository.yaml
INFO:  Pulled: sha256:214cc3cb5ede0e41da21e2eb94472a156ab83b244070f9e8086b1e671c1dfd3b
INFO:  Size: 634B
INFO:  Repository mocaccino-community is already up to date.
INFO:  ℹ  Repository: mocaccino-community Priority: 50 Type: docker
INFO:  Downloading quay.io/mocaccino/desktop:repository.yaml
INFO:  Pulled: sha256:8b14617db484fbec123aabf9a23db522a54fd1be9b1e6ab8458dc2de4d3f10d4
INFO:  Size: 633B
INFO:  Repository MocaccinoOS Desktop is already up to date.
INFO:  ℹ  Repository: mocaccino-desktop Priority: 3 Type: docker
INFO:  Downloading quay.io/mocaccino/extra:repository.yaml
INFO:  Pulled: sha256:49e64c4e1ff40bef1ec6c68e7976de99133a4354b936518533c3b763c8d7fc5d
INFO:  Size: 629B
INFO:  Repository mocaccino-extra is already up to date.
INFO:  ℹ  Repository: mocaccino-extra Priority: 2 Type: docker
INFO:  Downloading quay.io/mocaccino/kernel:repository.yaml
INFO:  Pulled: sha256:d84c91b693a926611e2262314b3ca3ead85c459a22aaf5795922461e6c1c67c3
INFO:  Size: 615B
INFO:  Repository  is already up to date.
INFO:  ℹ  Repository: mocaccino-kernel Priority: 3 Type: docker
INFO:  Downloading quay.io/mocaccino/os-commons:repository.yaml
INFO:  Pulled: sha256:a8ad99ac299430fdb9993378afc96bbddb4d5180cfd134ae0df7e370a0222e0e
INFO:  Size: 632B
INFO:  Repository example-repository is already up to date.
INFO:  ℹ  Repository: mocaccino-os-commons Priority: 2 Type: docker
INFO:  --- Search results (kde): ---
layers/kde-pim-21.04.3+52
layers/kde-apps-minimal-20.12.3+63
layers/kde-common-4+21
libs/kdegraphics-mobipocket-21.08.3

real    1m1.856s
user    2m2.559s
sys     0m2.652s`

As you can see it takes 1 minutes and 2 seconds to get a search result. This could be avoided I think.
Perhaps Luet already keeps a timestamp on when it synced repositories last time? Perhaps it could be smart enough to know it doesn't need to try download the repos all the time.

**Comment by mudler** [comment] 2021-12-15 17:19
Duplicate of #212

**Closed** 2021-12-18 16:30 UTC
Labels: enhancement
