### ISSUE TITLE
Respect existing system symbolic links

### ISSUE THREAD

**Issue by geaaru** [mudler/luet#231] opened 2021-06-19 09:49 UTC
**Luet version:**
all luet versions.

**Describe the bug**
If the system contains a link on existing rootfs, for example on ubuntu `/lib` is a link to `/usr/lib` , installing a package that supply file under `/usr/lib/systemd/` broken the system and is not more usable.

**To Reproduce**
Run a VM/Container with `ubuntu/20.10` and then install` www-apps/mottainai-dashboard` package or any package with systemD files.

**Expected behavior**
if the `/lib` is a link `luet` must maintains that link and install files under the expected path.

**Comment by mudler** [comment] 2021-06-19 09:51
Duplicate of #188

**Closed by mudler** 2021-06-19 09:51 UTC
Labels: bug
