### ISSUE TITLE
luet install should exit non-zero if it didn't find anything to install

### ISSUE THREAD

**Issue by optiz0r** [mudler/luet#152] opened 2020-11-26 23:26 UTC
When running `luet install foo`, the user has requested foo be installed. So luet should exit with non-zero status if when the command exits, foo is not installed.

Currently if foo is not matched to a package, luet will not install anything and the exit status is zero.

It should not be considered an error if foo is already installed.

**Comment by mudler** [comment] 2020-12-02 21:46
```
❯ docker run -ti --rm quay.io/mocaccino/extra                                                                                                                                                                                                

/ # luet install foobar/fooo
 Downloading https://raw.githubusercontent.com/Luet-lab/luet-repo/gh-pages/repository.yaml
⠉  Downloaded repository.yaml of 0.00 MB ( 0.00 MiB/s )
 Repository luet-official is already up to date.
 ℹ Repository: luet Priority: 1 Type: http
 Downloading https://get.mocaccino.org/mocaccino-extra/repository.yaml
⠖  Downloaded repository.yaml of 0.00 MB ( 0.00 MiB/s )
 Repository mocaccino-extra is already up to date.
 ℹ Repository: mocaccino-extra Priority: 2 Type: http
 Downloading https://get.mocaccino.org/mocaccino-micro/repository.yaml
⠦  Downloaded repository.yaml of 0.00 MB ( 0.00 MiB/s )
 Repository mocaccino-micro is already up to date.
⠒  ℹ Repository: mocaccino-micro Priority: 1 Type: http
 Downloading https://get.mocaccino.org/mocaccino-musl-universe/repository.yaml
⠈  Downloaded repository.yaml of 0.00 MB ( 0.00 MiB/s )
 Repository mocaccino-musl-universe is already up to date.
 ℹ Repository: mocaccino-musl-universe Priority: 2 Type: http
 Downloading https://raw.githubusercontent.com/mocaccinoOS/repository-index/gh-pages/repository.yaml
⠉  Downloaded repository.yaml of 0.00 MB ( 0.00 MiB/s )
 Repository mocaccino-repository-index is already up to date.
 ℹ Repository: mocaccino-repository-index Priority: 1 Type: http
 Error: Failed solving solution for package: Could not satisfy the constraints. Try again by removing deps 
/ # echo $?
1
```

I think the issue is here, when you provide two packages, and one of the two is matching: 
```bash
/ # luet install foobar/fooo utils/yq
⠈  Downloading https://raw.githubusercontent.com/Luet-lab/luet-repo/gh-pages/repository.yaml
⠋  Downloaded repository.yaml of 0.00 MB ( 0.00 MiB/s )
 Repository luet-official is already up to date.
 ℹ Repository: luet Priority: 1 Type: http
 Downloading https://get.mocaccino.org/mocaccino-extra/repository.yaml
⠖  Downloaded repository.yaml of 0.00 MB ( 0.00 MiB/s )
 Repository mocaccino-extra is already up to date.
 ℹ Repository: mocaccino-extra Priority: 2 Type: http
 Downloading https://get.mocaccino.org/mocaccino-micro/repository.yaml
⠦  Downloaded repository.yaml of 0.00 MB ( 0.00 MiB/s )
 Repository mocaccino-micro is already up to date.
⠒  ℹ Repository: mocaccino-micro Priority: 1 Type: http
 Downloading https://get.mocaccino.org/mocaccino-musl-universe/repository.yaml
⠈  Downloaded repository.yaml of 0.00 MB ( 0.00 MiB/s )
 Repository mocaccino-musl-universe is already up to date.
 ℹ Repository: mocaccino-musl-universe Priority: 2 Type: http
 Downloading https://raw.githubusercontent.com/mocaccinoOS/repository-index/gh-pages/repository.yaml
⠉  Downloaded repository.yaml of 0.00 MB ( 0.00 MiB/s )
 Repository mocaccino-repository-index is already up to date.
 ℹ Repository: mocaccino-repository-index Priority: 1 Type: http
 Packages that are going to be installed in the system: 
  utils/yq-3.4.1
 By going forward, you are also accepting the licenses of the packages that you are going to install in your system.
 Do you want to continue with this operation? [y/N]: 
```

**Comment by optiz0r** [comment] 2020-12-02 22:04
I think that should exit 1. The test is "did everything I ask it to do get done?" and the answer is no, because when the install command finishes, one is the two things I asked it to install is not installed.

I think it's fine if the one if the two was already installed, the result then when the command finishes is both are installed and my intent is satisfied.

**Comment by mudler** [comment] 2020-12-03 20:04
Should be fixed with the upcoming release which contains https://github.com/mudler/luet/commit/b17ac447f14437f2a8e3617e033d7118d17cfe02

**Closed** 2020-12-15 16:51 UTC
