### ISSUE TITLE
Weird Image Tag in case of building diamond dep

### ISSUE THREAD

**Issue by welele08** [mudler/luet#187] opened 2021-02-06 11:10 UTC
**Luet version:** 
luet version 0.10.2-g4eab1eb738c5698c42731f59f6edeaf52ca52956 2021-01-25 01:55:10 UTC

**CPU architecture, OS, and Version:**
sabayon on amd64, several docker container

**Describe the bug**
Luet computed hashtag for docker images seems wrong in case of a diamond build dependency. 
I try to build a package that depend on layers/qt and layers/gnome-common of desktop repo. It result in a change in hashtag of layers/qt docker image. The same happen when building over portage-tree repo.

**To Reproduce**
In a luet capable system :
- `git clone https://github.com/mocaccinoOS/desktop.git`
- Make a toy package called layers/A with build dep on layers/gnome-common and layers/qt (exemple in attachment)
- check images hash with `luet tree images -t  ./ layers/gnome-common` `luet tree images -t  ./ layers/qt``luet tree images -t  ./ layers/A`

Between second and third command, hash change for layers/qt.

**Expected behavior**
The same Hash so that `luet build`doesn't recompile qt.

**Additional context**
Replacing desktop by portage-tree give the same behavior. Which made me think of a luet bug or an me misunderstanding luet.
[A.zip](https://github.com/mudler/luet/files/5936626/A.zip)

**Comment by mudler** [comment] 2021-02-06 11:49
That's not a bug, but it's how it supposed to work:

If your toy package requires two images that doesn't have a shared deptree - it will form a new one, thus requiring the image to be rebuilt. Compare the dependency trees of qt and when you compile your package, you will likely find that they are different.

**Comment by mudler** [comment] 2021-02-11 18:38
Closing as it is working as supposed to. We have already #173 which would make the above issue less relevant. Feel free to re-open for further discussion, or if you have a suggestion on how to improve this.

**Closed by mudler** 2021-02-11 18:38 UTC
Labels: invalid
